Feat(task): Associate task to an sales_id
marmelab/atomic-crm pull request #25
Opened 2024-08-06 13:03 UTC by arimet

## Problem

Actually, you can only see Task that are associated with a contact that belongs to me.

## Solution

Associate Task to a sales_id. Display all Task for this sales in the Dashboard. 

- [x] The **documentation** is up to date

2024-08-06 16:07 UTC, slax57 reviewed
Also, needs rebase apparently

2024-08-06 16:07 UTC, slax57 commented on README.md
> +```
The improvements to the docs look good, but did you intend to include them in this PR? Neither the title nor the description speaks about that...

2024-08-06 16:07 UTC, slax57 commented on src/dashboard/TasksListFilter.tsx
> +                'sales_id@in': `(${identity?.id})`,
why keep the `in` operator here? :thinking: 

```suggestion
                sales_id: identity?.id,
```

2024-08-07 08:06 UTC, jonathan-marmelab reviewed
**nit-pick:** Since the readme file is getting large (and we sill have documentationto have), maybe we should split it into mutliple doc files under a doc directory and use the readme as table of contents ?

2024-08-07 08:08 UTC, jonathan-marmelab requested changes

2024-08-07 08:08 UTC, jonathan-marmelab commented on supabase/migrations/20240806124555_task_sales_id.sql
> +alter table "public"."tasks" add column "sales_id" bigint;
**issue:** You forgot to update the `Task` type in `types.ts` to reflect the change

2024-08-07 08:11 UTC, arimet commented
> **nit-pick:** Since the readme file is getting large (and we sill have documentationto have), maybe we should split it into mutliple doc files under a doc directory and use the readme as table of contents ?

Okay, but there's still a lot to document, and there's a ticket for that. I'm in favor of doing it then.

2024-08-07 08:17 UTC, slax57 commented on src/types.ts
> +    sales_id: Identifier;
Should be `sales_id?: Identifier;` since the column does not have the `not null` constraint in DB?

2024-08-07 08:32 UTC, jonathan-marmelab approved these changes

2024-08-07 12:42 UTC, merged