Module
marmelab/atomic-crm pull request #66
Opened 2024-09-13 14:30 UTC by ThieryMichel

## Problem

We cannot install atomic-crm from npm

## Solution

Add a lib build along the current app build with:
- esm 
- cjs
- types

## How To Test

To test without actually publishing the module:
- run npm pack to create an archive
- create a npm project, aor use an existing one
- add `"atomic-crm": "file://path-to-the-archive/atomic-crm-0.0.1.tgc"`
- run npm install
- start to play with the atomic-crm library
- Admire the type
- switch your project type between module and commonjs to use both version.
Note: only the CRM component is exposed for now 

## Additional Checks

- [ ] The **documentation** is up to date
- [ ] Tested with **fakerest** provider (see [related documentation](../doc/data-providers.md))

2024-09-13 15:58 UTC, fzaninotto requested changes
Excellent, thanks for that!

2024-09-13 15:58 UTC, fzaninotto commented on src/index.tsx
> +export default CRM;
**Nitcpick**: I'd prefer that we don't use the default export, in order to be able to export more than one component without breaking apps that used the first version of the package.

2024-09-16 10:06 UTC, fzaninotto approved these changes

2024-09-16 10:06 UTC, merged

2024-10-07 09:57 UTC, slax57 commented on makefile
> +
Shouldn't this be added to the `make build` target? I'm worried we risk forgetting to run `make build-lib`  next time we release the package to npm :grimacing:  .

2024-10-07 11:25 UTC, slax57 commented on makefile
> +
Actually both builds are separate: one is used to deploy the CRM app, the other is used to build the lib for npm. So keeping the 2 targets separate is a good thing.